# Configuraci칩n de Netlify para Vue.js + Vite

[build]
  # Comando para construir la aplicaci칩n
  command = "npm run build"
  
  # Directorio donde Vite genera el build
  publish = "dist"
  
  # Variables de entorno para el build
  [build.environment]
    NODE_VERSION = "20"

# Redirect rules para Single Page Application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers de seguridad y optimizaci칩n
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache para assets est치ticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
